### PR TITLE
added few url and sorted alphabetically

### PR DESCRIPTION
**Pull request by sigul**

### CODE REVIEW

**Comment by desbma** [comment]
I'm OK to merge, but can you explain how did you collect the new domains? I want to be sure there are no false positive.
Also I don't have the same sorting order, which sort program are you using (`sort --version`)?

**Comment by sigul** [comment]
domain that were hitting my website. 
I sorted them through sublime text sort line option

**Comment by desbma** [comment]
> domain that were hitting my website. 

How did you distinguish spam from legitimate referers?

> I sorted them through sublime text sort line option

It seems the sorting order is different from `sort`, I'll fix it during the merge.

**Comment by sigul** [comment]
I didn't launched the website, so all traffic arriving from site like adf.ly, social-buttons, black-friday.ga and so on was easy to note.

**Comment by desbma** [comment]
Merged, thanks

**Pull request merged**
