### PR TITLE
Detected new spammers

### PR DESCRIPTION
**Pull request by kapasite**
Detected new spammers

### CODE REVIEW

**Comment by desbma** [comment]
Thanks for the contribution.

Can you tell me how you have identified theses domains as referer spam?
Even if they clearly look like spammy domains, before merging I need to be sure we don't accidentally add a valid domain (false positive) in the process.

**Comment by kapasite** [comment]
My site's language is Turkish. But they are Russian and Ukrainian sites. And not my link in their sites.      My irrelevant and unpopular subpages hits from that subdomains and subpages. 

Traffic isn't organic. And from same IP addresses.

The attacks in bulk at certain times. 

I use goaccess analyzing tool. I think my diagnosis is correct. Sorry for  my basic  English.

**Comment by kapasite** [comment]
And the most important thing: They are not sending requests to my image and js files. Only to article urls.

**Comment by desbma** [comment]
All right, this is more than enough to justify adding them. :)

**Pull request merged**
